### ISSUE TITLE
请连接Android设备...

### ISSUE THREAD

**Issue by sqxiangxin** [azhon/screenshot#1]
请连接Android设备...

已打开调试模式，小米max3  MACOS 10.13.6 PyCharm

谢谢

**Comment by azhon** [comment]
连接电脑的时候看手机有没有弹出授权提示框框，连接电脑后将usb设为媒体模式

**Comment by sqxiangxin** [comment]
数据线连接手机 有提示音效（未弹出授权提示框） usb调试模式已打开。usb已设置为MTP(媒体传输协议)

**Comment by azhon** [comment]
那尝试换个手机或者重启手机试下

**Comment by sqxiangxin** [comment]
已解决，必须要用原装数据线。谢谢
